# Stateless application specification
# The Deployment creates a single replicated Pod, indicated by the 'replicas' field
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    anthos-migrate.cloud.google.com/type: linux-container
    app: instance-2
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.15.0
  name: instance-2
spec:
  replicas: 1
  selector:
    matchLabels:
      anthos-migrate.cloud.google.com/type: linux-container
      app: instance-2
      migrate-for-anthos-optimization: "true"
      migrate-for-anthos-version: v1.15.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        anthos-migrate.cloud.google.com/type: linux-container
        app: instance-2
        migrate-for-anthos-optimization: "true"
        migrate-for-anthos-version: v1.15.0
    spec:
      containers:
      - env:
        - name: HC_V2K_SERVICE_MANAGER
          value: "true"
        image: gcr.io/tvs-mob-test/instance-2:11-28-2023--9-6-35
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /gamma
            - probe
        name: instance-2
        readinessProbe:
          exec:
            command:
            - /gamma
            - probe
        resources: {}

---
# Headless Service specification -
# No load-balancing, and a single cluster internal IP, only reachable from within the cluster
# The Kubernetes endpoints controller will modify the DNS configuration to return records (addresses) that point to the Pods, which are labeled with "app": "instance-2"
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    anthos-migrate.cloud.google.com/type: linux-container
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.15.0
  name: instance-2
spec:
  clusterIP: None
  selector:
    app: instance-2
  type: ClusterIP

---